apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  labels:
    name: spring-boot
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: spring-boot
  type: LoadBalancer
