apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: gcr.io/gcp-brightlab/amar-poc/image_to_be_replace
          volumeMounts: 
          - mountPath: /spring-boot
            name: spring-boot-vol
          ports:
            - containerPort: 4000
      volumes:
        - name: spring-boot-vol
          gcePersistentDisk:
            pdName: jenkins-test
            fsType: ext4
