apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot
  namespace: bl-org
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: gcr.io/gcp-brightlab/amar-poc/image_to_be_replace
          ports:
            - containerPort: 4000
