apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: gcr.io/gcp-brightlab/amar-poc/spring-boot:1
          ports:
            - containerPort: 4000
